[project]
name = "EU-Chatbot"
version = "0.1.0"
description = "Unser toller Chatbot!"
readme = "README.md"
requires-python = "==3.12"
dependencies = [
    "llmling-agent[default]>=0.99.7",
    "streamlit>=1.42.0",
    "markitdown",
]
